logging:
    level:
        tk.mybatis: INFO
        package com.gospell.platform.oa.biz.user: INFO
        
spring:
    application:
        name: netease-song-rank
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/song_rank?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
        username: root
        password: 
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
management:
    security:
        enabled: false
    health:
      redis:
        enabled: false

mybatis:
    basepackage: me.olook.netease.song.rank.mapper
    xmlLocation: classpath:mapper/**/*.xml
    type-aliases-package: me.olook.netease.song.rank.entity
    configuration:
        map-underscore-to-camel-case: true

server:
    # HttpsConfiguration中有重定向端口配置
    port: 443
    ssl:
        key-store: /software/wxapp.olook.me.jks
        key-store-password: 
http:
    port: 80
    
flyway:
    baselineOnMigrate: true
    # 暂时关闭flyway校验
    # schema_version表存在时不做任何操作；不存在时清空已有数据，按照初始脚重新执行
    validateOnMigrate: false

swagger:
    basepackage: me.olook.netease.song.rank
    service:
        name: 定时任务服务
        description:  ·公用定时任务服务
        developer: red
wxapp:
    appId: 
    appSecret: 
    grantType: authorization_code
proxy:
    order-id: 
    pool-size: 10
    # 不加转义有毒 \&num=1\&delay=5\&filter=on
    option: \&num=1\&filter=on