logging:
    level:
        tk.mybatis: DEBUG
        package com.gospell.platform.oa.biz.user: DEBUG
        
spring:
    application:
        name: netease-song-rank
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/song_rank?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
        username: root
        password: 48STX2X
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    redis:
        database: 1
        #host: 127.0.0.1
        #docker
        host: redis
        pool:
            max-active: 20
management:
    security:
        enabled: false  

mybatis:
    basepackage: me.olook.netease.song.rank.mapper
    xmlLocation: classpath:mapper/**/*.xml
    type-aliases-package: me.olook.netease.song.rank.entity
    configuration:
        map-underscore-to-camel-case: true

server:
    # HttpsConfiguration中有重定向端口配置
    port: 8443
    ssl:
        key-store: /software/www.olook.me.jks
        key-store-password: wx55nc4ao9
http:
    port: 80
    
flyway:
    baselineOnMigrate: true
    # 暂时关闭flyway校验
    # schema_version表存在时不做任何操作；不存在时清空已有数据，按照初始脚重新执行
    # validateOnMigrate: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

swagger:
    basepackage: me.olook.netease.song.rank
    service:
        name: 定时任务服务
        description:  ·公用定时任务服务
        developer: zhw
wxapp:
    appId: wxd422e4a71b224d86
    appSecret: 
    grantType: authorization_code